/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ql_xe;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class EmployeeGUI extends javax.swing.JPanel {

    /**
     * Creates new form ..
     */
    public EmployeeGUI() {
        initComponents();
                
       
                
                
                
                
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        panelEmployeeID = new javax.swing.JPanel();
        txtEmployeeID = new RoundJTextField(30);
        labelEmployeeID = new javax.swing.JLabel();
        panelName = new javax.swing.JPanel();
        txtName = new RoundJTextField(30);
        labelName = new javax.swing.JLabel();
        panelWarrantyDate = new javax.swing.JPanel();
        labelWarrantyDate = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelRow1 = new javax.swing.JPanel();
        txtRow1 = new RoundJTextField(30);
        labelRow1 = new javax.swing.JLabel();
        panelRow2 = new javax.swing.JPanel();
        txtRow2 = new RoundJTextField(30);
        labelRow2 = new javax.swing.JLabel();
        buttonUpdate = new javax.swing.JButton();
        buttonSearch = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonAdd1 = new javax.swing.JButton();
        scrollTable = new javax.swing.JScrollPane();
        table = new rojeru_san.complementos.RSTableMetro();

        setPreferredSize(new java.awt.Dimension(1580, 770));

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("QUẢN LÝ NHÂN VIÊN");
        Main.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1580, 60));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Medium", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        Header.setPreferredSize(new java.awt.Dimension(1580, 770));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEmployeeID.setBackground(new java.awt.Color(255, 255, 255));
        panelEmployeeID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmployeeID.setBackground(new java.awt.Color(255, 255, 255));
        txtEmployeeID.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtEmployeeID.setForeground(new java.awt.Color(0, 0, 0));
        txtEmployeeID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmployeeID.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });
        panelEmployeeID.add(txtEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 270, 30));

        labelEmployeeID.setBackground(new java.awt.Color(255, 255, 255));
        labelEmployeeID.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelEmployeeID.setForeground(new java.awt.Color(0, 0, 0));
        labelEmployeeID.setText("Mã Nhân Viên:");
        panelEmployeeID.add(labelEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        Header.add(panelEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 480, 40));

        panelName.setBackground(new java.awt.Color(255, 255, 255));
        panelName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        panelName.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 270, 30));

        labelName.setBackground(new java.awt.Color(255, 255, 255));
        labelName.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelName.setForeground(new java.awt.Color(0, 0, 0));
        labelName.setText("Tên Nhân Viên:");
        panelName.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        Header.add(panelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 480, 40));

        panelWarrantyDate.setBackground(new java.awt.Color(255, 255, 255));
        panelWarrantyDate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelWarrantyDate.setBackground(new java.awt.Color(255, 255, 255));
        labelWarrantyDate.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelWarrantyDate.setForeground(new java.awt.Color(0, 0, 0));
        labelWarrantyDate.setText("Chức Vụ:");
        panelWarrantyDate.add(labelWarrantyDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        jComboBox1.setFont(new java.awt.Font("Bahnschrift", 1, 18));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên Hành Chính", "Nhân Viên Kĩ Thuật"}));
        panelWarrantyDate.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 270, 30));

        Header.add(panelWarrantyDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 480, 40));

        panelRow1.setBackground(new java.awt.Color(255, 255, 255));
        panelRow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRow1.setBackground(new java.awt.Color(255, 255, 255));
        txtRow1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtRow1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRow1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtRow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRow1ActionPerformed(evt);
            }
        });
        panelRow1.add(txtRow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 270, 30));

        labelRow1.setBackground(new java.awt.Color(255, 255, 255));
        labelRow1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelRow1.setForeground(new java.awt.Color(0, 0, 0));
        labelRow1.setText("Phòng Ban:");
        panelRow1.add(labelRow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        Header.add(panelRow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 480, 40));

        panelRow2.setBackground(new java.awt.Color(255, 255, 255));
        panelRow2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRow2.setBackground(new java.awt.Color(255, 255, 255));
        txtRow2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtRow2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRow2.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtRow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRow2ActionPerformed(evt);
            }
        });
        panelRow2.add(txtRow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 270, 30));

        labelRow2.setBackground(new java.awt.Color(255, 255, 255));
        labelRow2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelRow2.setForeground(new java.awt.Color(0, 0, 0));
        labelRow2.setText("Trình Độ Học Vấn:");
        panelRow2.add(labelRow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        Header.add(panelRow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 480, 40));

        buttonUpdate.setBackground(new java.awt.Color(255, 255, 255));
        buttonUpdate.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        buttonUpdate.setForeground(new java.awt.Color(0, 0, 0));
        buttonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-write-20.png"))); // NOI18N
        buttonUpdate.setText("SỬA");
        buttonUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonUpdate.setIconTextGap(15);
        Header.add(buttonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 140, 140, 40));

        buttonSearch.setBackground(new java.awt.Color(255, 255, 255));
        buttonSearch.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        buttonSearch.setForeground(new java.awt.Color(0, 0, 0));
        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-20.png"))); // NOI18N
        buttonSearch.setText("TÌM");
        buttonSearch.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonSearch.setIconTextGap(15);
        Header.add(buttonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 190, 140, 40));

        buttonDelete.setBackground(new java.awt.Color(255, 255, 255));
        buttonDelete.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(0, 0, 0));
        buttonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-20.png"))); // NOI18N
        buttonDelete.setText("XÓA");
        buttonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonDelete.setIconTextGap(15);
        Header.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 90, 140, 40));

        buttonAdd1.setBackground(new java.awt.Color(255, 255, 255));
        buttonAdd1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        buttonAdd1.setForeground(new java.awt.Color(0, 0, 0));
        buttonAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-50 (2) (2).png"))); // NOI18N
        buttonAdd1.setText("THÊM");
        buttonAdd1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonAdd1.setIconTextGap(15);
        Header.add(buttonAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 40, 140, 40));

        Main.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1558, 250));

        scrollTable.setBackground(new java.awt.Color(255, 255, 255));
        scrollTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setBorder(new javax.swing.border.MatteBorder(null));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ád", "ád", "ád", "ád"},
                {"áđá", "ád", "ád", "ád"},
                {"áđá", "d", "ád", "áđá"},
                {"áđá", "áđá", "áđá", "ád"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        table.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        table.setColorBordeHead(new java.awt.Color(255, 255, 255));
        table.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        table.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        table.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        table.setColorSelBackgound(new java.awt.Color(51, 51, 51));
        table.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        table.setFuenteFilas(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        table.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table.setGridColor(new java.awt.Color(0, 0, 0));
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table.setShowGrid(false);
        table.setShowVerticalLines(true);
        table.setSurrendersFocusOnKeystroke(true);
        table.getTableHeader().setReorderingAllowed(false);
        scrollTable.setViewportView(table);
        model = new DefaultTableModel(new String[] {"Mã Nhân Viên", "Tên Nhân Viên", "Chức Vụ", "Phòng Ban", "Trình Độ Học Vấn", "Bậc Thợ","Số Năm Kinh Nghiệm"},0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table.setModel(model);

        Main.add(scrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 1560, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 1584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    private void txtRow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRow1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRow1ActionPerformed

    private void txtRow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRow2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRow2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JButton buttonAdd1;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel labelEmployeeID;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelRow1;
    private javax.swing.JLabel labelRow2;
    private javax.swing.JLabel labelWarrantyDate;
    private javax.swing.JPanel panelEmployeeID;
    private javax.swing.JPanel panelName;
    private javax.swing.JPanel panelRow1;
    private javax.swing.JPanel panelRow2;
    private javax.swing.JPanel panelWarrantyDate;
    private javax.swing.JScrollPane scrollTable;
    private rojeru_san.complementos.RSTableMetro table;
    private javax.swing.JLabel title;
    public javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRow1;
    private javax.swing.JTextField txtRow2;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel model;
    
    
    
    
    public class RoundJTextField extends JTextField {
    private Shape shape;
    public RoundJTextField(int size) {
        super(size);
        setOpaque(false); // As suggested by @AVD in comment.
    }
    protected void paintComponent(Graphics g) {
         g.setColor(getBackground());
         g.fillRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
         super.paintComponent(g);
    }
    protected void paintBorder(Graphics g) {
         g.setColor(Color.BLACK);
         g.drawRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
    }
    public boolean contains(int x, int y) {
         if (shape == null || !shape.getBounds().equals(getBounds())) {
             shape = new RoundRectangle2D.Float(0, 0, getWidth()-1, getHeight()-1, 15, 15);
         }
         return shape.contains(x, y);
    }
}

    public class RoundBorderArea implements Border {

        private int radius;

        public RoundBorderArea(int radius) {
            this.radius = radius;
        }

        public int getRadius() {
            return radius;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            Graphics2D g2d = (Graphics2D) g.create();
            g2d.draw(new RoundRectangle2D.Double(x, y, width - 1, height - 1, getRadius(), getRadius()));
            g2d.dispose();
        }

        @Override
        public Insets getBorderInsets(Component c) {
            int value = getRadius() / 2;
            return new Insets(value, value, value, value);
        }

        @Override
        public boolean isBorderOpaque() {
            return false;
        }

    }
    
}
